version: '3'
services:
  app:
    build: .
    image: "minikube:5000/app:latest"
    ports:
      - "80:80"
    environment:
      GET_HOSTS_FROM: dns
    labels:
      kompose.service.type: LoadBalancer
  minio:
    image: "minio/minio:RELEASE.2020-03-19T21-49-00Z"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio1234"
      GET_HOSTS_FROM: dns
    command: server /data